# Generated by Django 4.0.4 on 2022-05-05 13:02

from django.db import migrations, models
from wallets.models import BitcoinAddress

def seed_data(apps, schema_editor):
    # BitcoinAddress = apps.get_model('wallets', 'BitcoinAddress')
    seedAddresses = [
        "3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd",
        "bc1q0sg9rdst255gtldsmcf8rk0764avqy2h2ksqs5",
        "12xQ9k5ousS8MqNsMBqHKtjAtCuKezm2Ju",
        "bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h",
    ]
    addressesToCreate = [BitcoinAddress(address=address) for address in seedAddresses]
    BitcoinAddress.objects.bulk_create(addressesToCreate)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('fromAddress', models.ManyToManyField(related_name='from_address', to='wallets.bitcoinaddress')),
                ('toAddress', models.ManyToManyField(related_name='to_address', to='wallets.bitcoinaddress')),
            ],
        ),
        migrations.RunPython(seed_data),
    ]
